--
-- PostgreSQL database dump
--

\restrict OlsextvpDQW1Q5T7k7JtboEJgkM9TqK6OE0LZvKSlfXboSMC1G5mnF5hKCI6eQa

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auditoria (
);


ALTER TABLE public.auditoria OWNER TO postgres;

--
-- Name: backup; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.backup (
);


ALTER TABLE public.backup OWNER TO postgres;

--
-- Name: modulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modulos (
    id_modulo integer NOT NULL,
    nombre_modulo character varying(80) NOT NULL,
    descripcion_modulo text
);


ALTER TABLE public.modulos OWNER TO postgres;

--
-- Name: permisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permisos (
    id_modulo integer NOT NULL,
    id_rol integer NOT NULL
);


ALTER TABLE public.permisos OWNER TO postgres;

--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol integer NOT NULL,
    nombre_rol character varying(80) NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesiones ; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."sesiones " (
);


ALTER TABLE public."sesiones " OWNER TO postgres;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    nombre_usuario character varying(30) NOT NULL,
    correo character varying(50) NOT NULL,
    clave character varying(250) NOT NULL,
    id_rol integer DEFAULT 1 NOT NULL,
    estatus boolean DEFAULT true NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_id_usuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_id_usuario_seq OWNER TO postgres;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_id_usuario_seq OWNED BY public.usuario.id_usuario;


--
-- Name: usuario id_usuario; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id_usuario SET DEFAULT nextval('public.usuario_id_usuario_seq'::regclass);


--
-- Data for Name: auditoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auditoria  FROM stdin;
\.


--
-- Data for Name: backup; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.backup  FROM stdin;
\.


--
-- Data for Name: modulos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.modulos (id_modulo, nombre_modulo, descripcion_modulo) FROM stdin;
1	gestionar_usuarios	Permite registrar, editar y dar de baja cuentas de usuario.
2	crear_divulgaciones	Autoriza la redacci¢n de alertas informativas clim ticas.
3	aprobar_divulgaciones	Opciones de moderaci¢n editorial para publicar en la cartelera.
\.


--
-- Data for Name: permisos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permisos (id_modulo, id_rol) FROM stdin;
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id_rol, nombre_rol) FROM stdin;
1	Superusuario
2	Administrador
3	Tecnico
\.


--
-- Data for Name: sesiones ; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."sesiones "  FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, nombre_usuario, correo, clave, id_rol, estatus) FROM stdin;
4	Aileen Moyeja	moyejada@gmail.com	scrypt:32768:8:1$gWzZ18QlcvRuH56c$0a7fe348ceafa52a0326fd19965ba51e22b36c541b562b7dd3031337e73c6f4e03d9d8b1a79600a329f4328c0d9e904da6609ddf7307f91fe48a436142c9614b	1	t
2	Mariangel Reyes	maruchan@gmail.com	scrypt:32768:8:1$dUzD64KmnHWQHxFJ$990ae5e50f714411534cd9b6b09a46d2c4329528f9c0f1f740c73b62ad0a4cf31aed48225dde644d0186386a250fc52a576494b196014e544d0eb25fe7b1ba6b	3	t
5	Gabriel Castaneda	gabrilucho@gmail.com	scrypt:32768:8:1$Uq0ne8CIh6hnPwDG$fff57d087028d0fc1ddfdbf97da69e7e1988a10a1f75afec178f2771bfcd3a5193c0ba251404ccab560ef0ad253dd16c4b945e48a6c7534cfefe3e33508e1dc0	2	t
6	Angel Ferrer	ferrari@gmai.com	scrypt:32768:8:1$phGcRoyNCk7gJBic$d913b62d15b95641502453909939d9866252401b276628cd328a5f1f746fcfc6e973c08d3f79fde566645c36ff2684641e7afd204f280405d71c185484e76744	3	t
7	Maria Perozo	negehip873@preparmy.com	scrypt:32768:8:1$DHQSJerYsEeL4mUJ$501b403056aa23b56c2427ea3514b01bc482b57c3ca4bb6a49b31d63eb4bec69cf6e4087b47d097f7c393d28ec28e7f42fd33adae06f8af19a3d8d681e952628	3	t
10	John Five	john@gmail.com	scrypt:32768:8:1$rggNN94L6bvC7q8P$514ac3d0bd14e48066ed414cb4c402b54acac97a69f38b93d4f83472e29f1be9a4c6d983cfbdb6dd7080002d55c5f2b7f2b2ea0cafbaf716bece9f361cef866e	2	t
11	Perez Jimenes	perez@gmail.com	scrypt:32768:8:1$HVytz31ePTHSTHmL$9abb7825be79244b56d1b7ab0066a166a606e0955ea00ed2f9f844e7c98716c230a0d3696fffe61ef69c8d68c9e7b555d96b23e0516263c9af877b386cee02c0	2	t
12	Genghis Khan	khan@gmail.com	scrypt:32768:8:1$GKE9E3BiXMmjRxcI$3c4038cbd204460f6a1302aff027a8dd7e3a150743b6b6c630a5e96542f9b9f9be31c27d835f5430812cd2341336debdf2511aa97b5c9437b23346b7ddc4d740	1	t
13	Morena Ramirez	m@gmail.com	scrypt:32768:8:1$mM3pgZVsAczkq4m0$0b0d882e4fd46398bcb41c8b36bc5fc00e0ebafcf27886f0f91f1e1d9500f93e948be70dfc543e42b9f5937d9afbe723cea8afbf5e70bee6dec156d6c48320e2	2	t
\.


--
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 4, true);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 13, true);


--
-- Name: modulos modulos_nombre_modulo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulos
    ADD CONSTRAINT modulos_nombre_modulo_key UNIQUE (nombre_modulo);


--
-- Name: modulos modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modulos
    ADD CONSTRAINT modulos_pkey PRIMARY KEY (id_modulo);


--
-- Name: permisos permisos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT permisos_pkey PRIMARY KEY (id_modulo, id_rol);


--
-- Name: rol rol_nombre_rol_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_nombre_rol_key UNIQUE (nombre_rol);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: permisos fk_permisos_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
    ADD CONSTRAINT fk_permisos_rol FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict OlsextvpDQW1Q5T7k7JtboEJgkM9TqK6OE0LZvKSlfXboSMC1G5mnF5hKCI6eQa

