"""Crear base de datos limpia

Revision ID: 782178008bd1
Revises: 
Create Date: 2026-06-07 12:46:08.453490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782178008bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('actividad', sa.String(length=180), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estado_geo', sa.String(length=80), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=False),
    sa.Column('parroquia', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('acuerdos', sa.Text(), nullable=True),
    sa.Column('minuta_archivo', sa.String(length=255), nullable=True),
    sa.Column('fotos_archivos', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitacora_transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=40), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('nombre_estado')
    )
    op.create_table('inventario_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_equipo', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=False),
    sa.Column('estado_operativo', sa.String(length=60), nullable=False),
    sa.Column('estado_flujo', sa.String(length=20), nullable=False),
    sa.Column('ultimo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('mapas_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_mapa', sa.String(length=40), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('cobertura', sa.String(length=120), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modulos',
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('nombre_modulo', sa.String(length=80), nullable=False),
    sa.Column('descripcion_modulo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_modulo'),
    sa.UniqueConstraint('nombre_modulo')
    )
    op.create_table('nivel',
    sa.Column('id_nivel', sa.Integer(), nullable=False),
    sa.Column('nombre_nivel', sa.String(length=80), nullable=False),
    sa.Column('descripción ', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_nivel'),
    sa.UniqueConstraint('nombre_nivel')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('publicado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_transaccionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('modulo_origen', sa.String(length=50), nullable=False),
    sa.Column('rango_desde', sa.Date(), nullable=True),
    sa.Column('rango_hasta', sa.Date(), nullable=True),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('visitas_portal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitas_portal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitas_portal_mes'), ['mes'], unique=False)

    op.create_table('municipio',
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre_municipio', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado.id_estado'], ),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_table('permiso',
    sa.Column('id_modulo', sa.Integer(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], )
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=30), nullable=False),
    sa.Column('clave usuario', sa.String(length=255), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('parroquia',
    sa.Column('id_parroquia', sa.Integer(), nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('nombre_parroquia', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_parroquia')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('comunidad',
    sa.Column('id_comunidad', sa.Integer(), nullable=False),
    sa.Column('id_parroquia', sa.Integer(), nullable=False),
    sa.Column('nombre_comunidad', sa.String(length=180), nullable=False),
    sa.ForeignKeyConstraint(['id_parroquia'], ['parroquia.id_parroquia'], ),
    sa.PrimaryKeyConstraint('id_comunidad')
    )
    op.create_table('actividad',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('fecha_actividad', sa.Date(), nullable=False),
    sa.Column('tipo_actividad', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('id_comunidad', sa.Integer(), nullable=False),
    sa.Column('id_nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidad'], ['comunidad.id_comunidad'], ),
    sa.ForeignKeyConstraint(['id_nivel'], ['nivel.id_nivel'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_table('intitucion',
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('id_comunidad', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=50), nullable=False),
    sa.Column('tipo_intitucion', sa.String(length=20), nullable=False),
    sa.Column('direccion_exacta', sa.String(length=100), nullable=False),
    sa.Column('numero_contacto', sa.String(length=25), nullable=False),
    sa.Column('correo_electronico', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['id_comunidad'], ['comunidad.id_comunidad'], ),
    sa.PrimaryKeyConstraint('id_institucion')
    )
    op.create_table('formacion',
    sa.Column('id_formacion', sa.Integer(), nullable=False),
    sa.Column('nombre_formacion', sa.Text(), nullable=False),
    sa.Column('id_actividad ', sa.Integer(), nullable=False),
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_actividad '], ['actividad.id_actividad'], ),
    sa.ForeignKeyConstraint(['id_institucion'], ['intitucion.id_institucion'], ),
    sa.PrimaryKeyConstraint('id_formacion'),
    sa.UniqueConstraint('id_actividad ')
    )
    op.create_table('sensibilizacion ',
    sa.Column('id_sensivilizacion', sa.Integer(), nullable=False),
    sa.Column('nombre_sensivilizacion', sa.Text(), nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividad.id_actividad'], ),
    sa.PrimaryKeyConstraint('id_sensivilizacion'),
    sa.UniqueConstraint('id_actividad')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensibilizacion ')
    op.drop_table('formacion')
    op.drop_table('intitucion')
    op.drop_table('actividad')
    op.drop_table('comunidad')
    op.drop_table('password_resets')
    op.drop_table('parroquia')
    op.drop_table('usuario')
    op.drop_table('permiso')
    op.drop_table('municipio')
    with op.batch_alter_table('visitas_portal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitas_portal_mes'))

    op.drop_table('visitas_portal')
    op.drop_table('roles')
    op.drop_table('reportes_transaccionales')
    op.drop_table('publicaciones')
    op.drop_table('nivel')
    op.drop_table('modulos')
    op.drop_table('mapas_registro')
    op.drop_table('inventario_equipos')
    op.drop_table('estado')
    op.drop_table('bitacora_transacciones')
    op.drop_table('actividades')
    # ### end Alembic commands ###
