"""Crear tablas roles permisos bitacora

Revision ID: 935e8e94b01b
Revises: 
Create Date: 2026-05-17 13:57:49.246400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935e8e94b01b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], )
    )
    op.drop_table('comunidades')
    op.drop_table('formaciones')
    op.drop_table('sensibilizaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensibilizaciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('campana', sa.VARCHAR(length=150), nullable=False),
    sa.Column('territorio', sa.VARCHAR(length=120), nullable=False),
    sa.Column('vocero', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('alcance', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formaciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tema', sa.VARCHAR(length=150), nullable=False),
    sa.Column('comunidad', sa.VARCHAR(length=120), nullable=False),
    sa.Column('facilitador', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('asistentes', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.Column('creado_en', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunidades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=180), nullable=False),
    sa.Column('vocero', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=40), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=80), nullable=False),
    sa.Column('municipio', sa.VARCHAR(length=120), nullable=False),
    sa.Column('parroquia', sa.VARCHAR(length=120), nullable=True),
    sa.Column('familias', sa.INTEGER(), nullable=False),
    sa.Column('fase', sa.VARCHAR(length=60), nullable=False),
    sa.Column('fecha_proximo', sa.DATE(), nullable=True),
    sa.Column('creado_en', sa.DATETIME(), nullable=False),
    sa.Column('actualizado_en', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
