"""Agregar cedula y especialidad a usuario

Revision ID: a6b7f3a058e2
Revises: 7653e1663a01
Create Date: 2026-06-11 00:32:51.786469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b7f3a058e2'
down_revision = '7653e1663a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('especialidad', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('especialidad')
        batch_op.drop_column('cedula')

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
