"""Añadir id_nivel a actividad

Revision ID: dc4ff1e3848b
Revises: c3d4e5f6a7b8
Create Date: 2026-09-02 12:18:37.161627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc4ff1e3848b'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora_transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=40), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_equipo',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('ubicacion_origen', sa.String(length=100), nullable=False),
    sa.Column('ubicacion_destino', sa.String(length=100), nullable=False),
    sa.Column('motivo_responsable', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_material_nivel'))
        batch_op.drop_index(batch_op.f('idx_material_tema'))

    op.drop_table('material')
    op.drop_table('modelo')
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_movimientos_equipo'))
        batch_op.drop_index(batch_op.f('idx_movimientos_ubic_destino'))
        batch_op.drop_index(batch_op.f('idx_movimientos_ubic_origen'))

    op.drop_table('movimientos')
    with op.batch_alter_table('equipo_monitoreo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_eq_monitoreo_equipo'))
        batch_op.drop_index(batch_op.f('idx_eq_monitoreo_monitoreo'))

    op.drop_table('equipo_monitoreo')
    op.drop_table('marca')
    op.drop_table('spatial_ref_sys')
    op.drop_table('tema')
    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_nivel', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('actividad_fecha_actividad_tipo_actividad_id_comunidad_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('actividad_id_y_tipo_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_actividad_comunidad'))
        batch_op.drop_constraint(batch_op.f('actividad_id_comunidad_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comunidad', ['id_comunidad'], ['id_comunidad'])
        batch_op.create_foreign_key(None, 'nivel', ['id_nivel'], ['id_nivel'])

    with op.batch_alter_table('actividad_tecnico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_act_tec_actividad'))
        batch_op.drop_index(batch_op.f('idx_act_tec_tecnico'))
        batch_op.drop_constraint(batch_op.f('actividad_tecnico_id_tecnico_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('actividad_tecnico_id_actividad_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tecnicos', ['id_tecnico'], ['id_tecnico'])
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])

    with op.batch_alter_table('catalogo_simbologia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_simbologia_categoria'))

    with op.batch_alter_table('comunidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comunidad_parroquia'))
        batch_op.drop_constraint(batch_op.f('comunidad_id_parroquia_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'parroquia', ['id_parroquia'], ['id_parroquia'])

    with op.batch_alter_table('divulgacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('divulgacion_id_actividad_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('divulgacion_id_actividad_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])

    with op.batch_alter_table('elementos_mapariesgo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_elementos_geom'), postgresql_using='gist')
        batch_op.drop_constraint(batch_op.f('elementos_mapariesgo_id_mapa_riesgo_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mapas_riesgo', ['id_mapa_riesgo'], ['id_mapa_riesgo'])

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('ultimo_mantenimiento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('responsable', sa.String(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('idx_equipo_modelo'))
        batch_op.drop_index(batch_op.f('idx_equipo_ubicacion_actual'))
        batch_op.drop_constraint(batch_op.f('equipo_id_modelos_equipos_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('equipo_id_ubicacion_actual_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ubicacion', ['id_ubicacion_actual'], ['id_ubicacion'])
        batch_op.create_foreign_key(None, 'modelos_equipo', ['id_modelos_equipos'], ['id_modelos_equipo'])

    with op.batch_alter_table('formacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_formacion_institucion'))
        batch_op.drop_constraint(batch_op.f('formacion_id_nivel_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('formacion_actividad_compuesta_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institucion', ['id_institucion'], ['id_institucion'])
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])
        batch_op.create_foreign_key(None, 'nivel', ['id_nivel'], ['id_nivel'])

    with op.batch_alter_table('imagenes_actividad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_img_act_actividad'))
        batch_op.drop_index(batch_op.f('idx_img_act_imagen'))
        batch_op.drop_constraint(batch_op.f('imagenes_actividad_id_imagen_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('imagenes_actividad_id_actividad_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])
        batch_op.create_foreign_key(None, 'imagenes', ['id_imagen'], ['id_imagen'])

    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_institucion_comunidad'))
        batch_op.drop_constraint(batch_op.f('institucion_id_comunidad_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comunidad', ['id_comunidad'], ['id_comunidad'])

    with op.batch_alter_table('mapa_climatico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fki_mapa_climatico_id_estado_fkey'))
        batch_op.drop_constraint(batch_op.f('mapa_climatico_id_estado_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estado', ['id_estado'], ['id_estado'])

    with op.batch_alter_table('mapas_riesgo', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('poligonal_comunidad',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
        batch_op.alter_column('tipo_actividad',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_mapa_actividad'))
        batch_op.drop_index(batch_op.f('idx_mapa_poligonal'), postgresql_using='gist')
        batch_op.drop_index(batch_op.f('idx_mapas_riesgo_poligonal'), postgresql_using='gist')
        batch_op.create_index('idx_mapas_riesgo_poligonal_comunidad', ['poligonal_comunidad'], unique=False, postgresql_using='gist')
        batch_op.drop_constraint(batch_op.f('fk_mapas_riesgo_actividad'), type_='foreignkey')
        batch_op.create_foreign_key('fk_mapas_riesgo_actividad', 'actividad', ['id_actividad', 'tipo_actividad'], ['id_actividad', 'tipo_actividad'])

    with op.batch_alter_table('modelos_equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=False))
        batch_op.drop_index(batch_op.f('idx_modelos_categoria'))
        batch_op.drop_index(batch_op.f('idx_modelos_modelo'), postgresql_with={'deduplicate_items': 'true'})
        batch_op.drop_constraint(batch_op.f('listado_equipo_id_modelo_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('modelos_equipo_id_categoria_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categoria', ['id_categoria'], ['id_categoria'])
        batch_op.drop_column('id_modelo')

    with op.batch_alter_table('monitoreo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('monitoreo_actividad_compuesta_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])

    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_municipio_estado'))
        batch_op.drop_constraint(batch_op.f('municipio_id_estado_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estado', ['id_estado'], ['id_estado'])

    with op.batch_alter_table('parroquia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_parroquia_municipio'))
        batch_op.drop_constraint(batch_op.f('parroquia_id_municipio_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipio', ['id_municipio'], ['id_municipio'])

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_publicaciones_divulgacion'))
        batch_op.drop_constraint(batch_op.f('publicaciones_id_divulgacion_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'divulgacion', ['id_divulgacion'], ['id_divulgacion'])

    with op.batch_alter_table('registros_climaticos', schema=None) as batch_op:
        batch_op.alter_column('temperatura',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('precipitaciones',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('vientos',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('humedad',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_regcli_equipo'))
        batch_op.drop_index(batch_op.f('idx_regcli_mapa'))
        batch_op.drop_constraint(batch_op.f('registros_climaticos_id_equipo_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('registros_climaticos_id_mapa_climatico_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipo', ['id_equipo'], ['id_equipo'])
        batch_op.create_foreign_key(None, 'mapa_climatico', ['id_mapa_climatico'], ['id_mapa_climatico'])

    with op.batch_alter_table('sensibilizacion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sensibilizacion_id_nivel_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sensibilizacion_actividad_compuesta_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'nivel', ['id_nivel'], ['id_nivel'])
        batch_op.create_foreign_key(None, 'actividad', ['id_actividad'], ['id_actividad'])

    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('tecnicos_cedula_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['id_usuario'])

    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ubicacion_parroquia'))
        batch_op.drop_constraint(batch_op.f('ubicacion_id_parroquia_fkey'), type_='foreignkey')
        batch_op.drop_column('geom')

    with op.batch_alter_table('visitas_portal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitas_portal_mes'), ['mes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas_portal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitas_portal_mes'))

    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('ubicacion_id_parroquia_fkey'), 'parroquia', ['id_parroquia'], ['id_parroquia'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_ubicacion_parroquia'), ['id_parroquia'], unique=False)

    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('tecnicos_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('especialidad')

    with op.batch_alter_table('sensibilizacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sensibilizacion_actividad_compuesta_fkey'), 'actividad', ['id_actividad', 'tipo_actividad'], ['id_actividad', 'tipo_actividad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('sensibilizacion_id_nivel_fkey'), 'nivel', ['id_nivel'], ['id_nivel'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('registros_climaticos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registros_climaticos_id_mapa_climatico_fkey'), 'mapa_climatico', ['id_mapa_climatico'], ['id_mapa_climatico'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('registros_climaticos_id_equipo_fkey'), 'equipo', ['id_equipo'], ['id_equipo'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_regcli_mapa'), ['id_mapa_climatico'], unique=False)
        batch_op.create_index(batch_op.f('idx_regcli_equipo'), ['id_equipo'], unique=False)
        batch_op.alter_column('humedad',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('vientos',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('precipitaciones',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('publicaciones_id_divulgacion_fkey'), 'divulgacion', ['id_divulgacion'], ['id_divulgacion'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_publicaciones_divulgacion'), ['id_divulgacion'], unique=False)
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('parroquia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('parroquia_id_municipio_fkey'), 'municipio', ['id_municipio'], ['id_municipio'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_parroquia_municipio'), ['id_municipio'], unique=False)

    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('municipio_id_estado_fkey'), 'estado', ['id_estado'], ['id_estado'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_municipio_estado'), ['id_estado'], unique=False)

    with op.batch_alter_table('monitoreo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('monitoreo_actividad_compuesta_fkey'), 'actividad', ['id_actividad', 'tipo_actividad'], ['id_actividad', 'tipo_actividad'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('modelos_equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_modelo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('modelos_equipo_id_categoria_fkey'), 'categoria', ['id_categoria'], ['id_categoria'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('listado_equipo_id_modelo_fkey'), 'modelo', ['id_modelo'], ['id_modelo'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_modelos_modelo'), ['id_modelo'], unique=False, postgresql_with={'deduplicate_items': 'true'})
        batch_op.create_index(batch_op.f('idx_modelos_categoria'), ['id_categoria'], unique=False)
        batch_op.drop_column('marca')
        batch_op.drop_column('modelo')

    with op.batch_alter_table('mapas_riesgo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mapas_riesgo_actividad', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mapas_riesgo_actividad'), 'actividad', ['id_actividad', 'tipo_actividad'], ['id_actividad', 'tipo_actividad'], ondelete='RESTRICT')
        batch_op.drop_index('idx_mapas_riesgo_poligonal_comunidad', postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_mapas_riesgo_poligonal'), ['poligonal_comunidad'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_mapa_poligonal'), ['poligonal_comunidad'], unique=False, postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_mapa_actividad'), ['id_actividad'], unique=False)
        batch_op.alter_column('tipo_actividad',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('poligonal_comunidad',
               existing_type=geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('mapa_climatico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mapa_climatico_id_estado_fkey'), 'estado', ['id_estado'], ['id_estado'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('fki_mapa_climatico_id_estado_fkey'), ['id_estado'], unique=False)

    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('institucion_id_comunidad_fkey'), 'comunidad', ['id_comunidad'], ['id_comunidad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_institucion_comunidad'), ['id_comunidad'], unique=False)

    with op.batch_alter_table('imagenes_actividad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imagenes_actividad_id_actividad_fkey'), 'actividad', ['id_actividad'], ['id_actividad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('imagenes_actividad_id_imagen_fkey'), 'imagenes', ['id_imagen'], ['id_imagen'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_img_act_imagen'), ['id_imagen'], unique=False)
        batch_op.create_index(batch_op.f('idx_img_act_actividad'), ['id_actividad'], unique=False)

    with op.batch_alter_table('formacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('formacion_actividad_compuesta_fkey'), 'actividad', ['id_actividad', 'tipo_actividad'], ['id_actividad', 'tipo_actividad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('formacion_id_nivel_fkey'), 'nivel', ['id_nivel'], ['id_nivel'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_formacion_institucion'), ['id_institucion'], unique=False)

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipo_id_ubicacion_actual_fkey'), 'ubicacion', ['id_ubicacion_actual'], ['id_ubicacion'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('equipo_id_modelos_equipos_fkey'), 'modelos_equipo', ['id_modelos_equipos'], ['id_modelos_equipo'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_equipo_ubicacion_actual'), ['id_ubicacion_actual'], unique=False)
        batch_op.create_index(batch_op.f('idx_equipo_modelo'), ['id_modelos_equipos'], unique=False)
        batch_op.drop_column('responsable')
        batch_op.drop_column('ultimo_mantenimiento')
        batch_op.drop_column('condicion')

    with op.batch_alter_table('elementos_mapariesgo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('elementos_mapariesgo_id_mapa_riesgo_fkey'), 'mapas_riesgo', ['id_mapa_riesgo'], ['id_mapa_riesgo'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_elementos_geom'), ['geom'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('divulgacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('divulgacion_id_actividad_fkey'), 'actividad', ['id_actividad'], ['id_actividad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_unique_constraint(batch_op.f('divulgacion_id_actividad_key'), ['id_actividad'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('comunidad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comunidad_id_parroquia_fkey'), 'parroquia', ['id_parroquia'], ['id_parroquia'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_comunidad_parroquia'), ['id_parroquia'], unique=False)

    with op.batch_alter_table('catalogo_simbologia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_simbologia_categoria'), ['categoria'], unique=False)

    with op.batch_alter_table('actividad_tecnico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('actividad_tecnico_id_actividad_fkey'), 'actividad', ['id_actividad'], ['id_actividad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('actividad_tecnico_id_tecnico_fkey'), 'tecnicos', ['id_tecnico'], ['id_tecnico'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_act_tec_tecnico'), ['id_tecnico'], unique=False)
        batch_op.create_index(batch_op.f('idx_act_tec_actividad'), ['id_actividad'], unique=False)

    with op.batch_alter_table('actividad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('actividad_id_comunidad_fkey'), 'comunidad', ['id_comunidad'], ['id_comunidad'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_actividad_comunidad'), ['id_comunidad'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('actividad_id_y_tipo_key'), ['id_actividad', 'tipo_actividad'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('actividad_fecha_actividad_tipo_actividad_id_comunidad_key'), ['fecha_actividad', 'tipo_actividad', 'id_comunidad'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('id_nivel')

    op.create_table('tema',
    sa.Column('id_tema', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_tema', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion_tema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_tema', name=op.f('tema_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('marca',
    sa.Column('id_marca', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_marca', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_marca', name=op.f('marca_pkey'))
    )
    op.create_table('equipo_monitoreo',
    sa.Column('id_monitoreo_equipo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_monitoreo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], name=op.f('equipo_monitoreo_id_equipo_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_monitoreo'], ['monitoreo.id_monitoreo'], name=op.f('equipo_monitoreo_id_monitoreo_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_monitoreo_equipo', name=op.f('equipo_monitoreo_pkey'))
    )
    with op.batch_alter_table('equipo_monitoreo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_eq_monitoreo_monitoreo'), ['id_monitoreo'], unique=False)
        batch_op.create_index(batch_op.f('idx_eq_monitoreo_equipo'), ['id_equipo'], unique=False)

    op.create_table('movimientos',
    sa.Column('id_movimientos', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_ubicacion_origen', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_ubicacion_destino', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_operacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_movimiento', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], name=op.f('movimientos_id_equipo_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_ubicacion_destino'], ['ubicacion.id_ubicacion'], name=op.f('movimientos_id_ubicacion_destino_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_movimientos', name=op.f('movimientos_pkey'))
    )
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_movimientos_ubic_origen'), ['id_ubicacion_origen'], unique=False)
        batch_op.create_index(batch_op.f('idx_movimientos_ubic_destino'), ['id_ubicacion_destino'], unique=False)
        batch_op.create_index(batch_op.f('idx_movimientos_equipo'), ['id_equipo'], unique=False)

    op.create_table('modelo',
    sa.Column('id_modelo', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_marca', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id_marca'], name=op.f('modelo_id_marca_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_modelo', name=op.f('modelo_pkey'))
    )
    op.create_table('material',
    sa.Column('id_material', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_nivel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_tema', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_nivel'], ['nivel.id_nivel'], name=op.f('material_id_nivel_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_tema'], ['tema.id_tema'], name=op.f('material_id_tema_fkey'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_material', name=op.f('material_pkey'))
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_material_tema'), ['id_tema'], unique=False)
        batch_op.create_index(batch_op.f('idx_material_nivel'), ['id_nivel'], unique=False)

    op.drop_table('movimiento_equipo')
    op.drop_table('bitacora_transacciones')
    # ### end Alembic commands ###
